version: '1.0'
services:
  nginx:
    ports:
      - 8000:8080
      - 21:21
    restart: always
  localstack:
    restart: always
  postgres:
    restart: always
  redis:
    restart: always
  redis-cache:
    restart: always
