version: "3.8"

services:

  localstack:
    image: localstack/localstack-full
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=lambda,s3,ec2
    ports:
      - '8080:8080'
    volumes:
      - "/var/lib/localstack"
#      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"
